services:
  web:
    container_name: "salt-lite-app-web"
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    platform: linux/amd64
    ports:
      - "${DOCKER_HOST_HTTP_PORT:-8000}:80"
    depends_on:
      - mysql
      - redis
      - rabbitmq
    volumes:
      - ${SOURCE_DIR:-./}:/var/www/
      - ./php-development.ini:/usr/local/etc/php/conf.d/settings.ini
    env_file:
      - .env
    environment:
      PHP_IDE_CONFIG: "serverName=cli" # Used by PhpStorm for path mapping
      COMPOSER_AUTH: "{\"github-oauth\": {\"github.com\":\"${GITHUB_TOKEN}\"}}"
    extra_hosts:
      - host.docker.internal:host-gateway

  mysql:
    container_name: "salt-lite-app-mysql"
    image: mysql:8.0.36
    platform: linux/amd64
    ports:
      - "${DOCKER_HOST_MYSQL_PORT:-3306}:3306"
    volumes:
      - ./database/seed/:/docker-entrypoint-initdb.d/
    tmpfs:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${SALT_MYSQL_ROOT_PASS:-pb_pass123}"
      MYSQL_DATABASE: "${SALT_MYSQL_NAME:-salt-lite-app}"
      MYSQL_USER: "${SALT_MYSQL_USER:-pb_user}"
      MYSQL_PASSWORD: "${SALT_MYSQL_PASS:-pb_pass}"

  redis:
    container_name: "salt-lite-app-redis"
    image: redis:7
    platform: linux/amd64
    ports:
      - "${DOCKER_HOST_REDIS_PORT:-63791}:6379"

  rabbitmq:
    container_name: "salt-lite-app-rabbitmq"
    image: rabbitmq:management
    platform: linux/amd64
    ports:
      - "${DOCKER_HOST_RABBITMQ_MANAGEMENT_PORT:-15672}:15672"
      - "${DOCKER_HOST_RABBITMQ_PORT:-5672}:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "${SALT_RABBITMQ_USER:-user}"
      RABBITMQ_DEFAULT_PASS: "${SALT_RABBITMQ_PASS:-password}"

  mailhog:
    container_name: "salt-lite-app-mailhog"
    image: mailhog/mailhog:latest
    platform: linux/amd64
    ports:
      - "${DOCKER_HOST_MAILHOG_SMTP_PORT:-1025}:1025"
      - "${DOCKER_HOST_MAILHOG_HTTP_PORT:-8025}:8025"